# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
        -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: '5.0.3'
    hooks:
        -   id: flake8
-   repo: local
    hooks:
        -   id: pytest-check
            name: pytest-check
            entry: pytest -s --client mock
            language: system
            pass_filenames: false
            always_run: true
